import { Inter } from "next/font/google";
import "./globals.css";
// import { SDKProvider } from '@tma.js/sdk-react';


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* <SDKProvider acceptCustomStyles debug> */}
      <body className={inter.className}>{children}</body>
      {/* </SDKProvider> */}
    </html>
  );
}
